import PlusIconSvg from "./plus.svg";
import CloseIconSvg from "./close.svg";
import BoxIconSvg from "./box.svg";
import CheckCircleIconSvg from "./check-circle.svg";
import AlertIconSvg from "./alert.svg";
import InfoIconSvg from "./info.svg";
import ErrorIconSvg from "./info-hexa.svg";
import BoltIconSvg from "./bolt.svg";
import ArrowUpIconSvg from "./arrow-up.svg";
import ArrowDownIconSvg from "./arrow-down.svg";
import FolderIconSvg from "./folder.svg";
import VideoIconSvg from "./videos.svg";
import AudioIconSvg from "./audio.svg";
import GridIconSvg from "./grid.svg";
import FileIconSvg from "./file.svg";
import DownloadIconSvg from "./download.svg";
import ArrowRightIconSvg from "./arrow-right.svg";
import GroupIconSvg from "./group.svg";
import BoxIconLineSvg from "./box-line.svg";
import ShootingStarIconSvg from "./shooting-star.svg";
import DollarLineIconSvg from "./dollar-line.svg";
import TrashBinIconSvg from "./trash.svg";
import AngleUpIconSvg from "./angle-up.svg";
import AngleDownIconSvg from "./angle-down.svg";
import PencilIconSvg from "./pencil.svg";
import CheckLineIconSvg from "./check-line.svg";
import CloseLineIconSvg from "./close-line.svg";
import ChevronDownIconSvg from "./chevron-down.svg";
import ChevronUpIconSvg from "./chevron-up.svg";
import PaperPlaneIconSvg from "./paper-plane.svg";
import LockIconSvg from "./lock.svg";
import EnvelopeIconSvg from "./envelope.svg";
import UserIconSvg from "./user-line.svg";
import CalenderIconSvg from "./calender-line.svg";
import EyeIconSvg from "./eye.svg";
import EyeCloseIconSvg from "./eye-close.svg";
import TimeIconSvg from "./time.svg";
import CopyIconSvg from "./copy.svg";
import ChevronLeftIconSvg from "./chevron-left.svg";
import UserCircleIconSvg from "./user-circle.svg";
import TaskIconSvg from "./task-icon.svg";
import ListIconSvg from "./list.svg";
import TableIconSvg from "./table.svg";
import PageIconSvg from "./page.svg";
import PieChartIconSvg from "./pie-chart.svg";
import BoxCubeIconSvg from "./box-cube.svg";
import PlugInIconSvg from "./plug-in.svg";
import DocsIconSvg from "./docs.svg";
import MailIconSvg from "./mail-line.svg";
import HorizontaLDotsSvg from "./horizontal-dots.svg";
import ChatIconSvg from "./chat.svg";
import MoreDotIconSvg from "./more-dot.svg";
import BellIconSvg from "./bell.svg";
import Image from "next/image";

function createIconComponent(src: string, alt: string) {
  return function Icon(props: { width?: number; height?: number; className?: string }) {
    const { width = 24, height = 24, className } = props;
    return <Image src={src} alt={alt} width={width} height={height} className={className} />;
  };
}

export const DownloadIcon = createIconComponent(DownloadIconSvg, "Download Icon");
export const BellIcon = createIconComponent(BellIconSvg, "Bell Icon");
export const MoreDotIcon = createIconComponent(MoreDotIconSvg, "More Dot Icon");
export const FileIcon = createIconComponent(FileIconSvg, "File Icon");
export const GridIcon = createIconComponent(GridIconSvg, "Grid Icon");
export const AudioIcon = createIconComponent(AudioIconSvg, "Audio Icon");
export const VideoIcon = createIconComponent(VideoIconSvg, "Video Icon");
export const BoltIcon = createIconComponent(BoltIconSvg, "Bolt Icon");
export const PlusIcon = createIconComponent(PlusIconSvg, "Plus Icon");
export const BoxIcon = createIconComponent(BoxIconSvg, "Box Icon");
export const CloseIcon = createIconComponent(CloseIconSvg, "Close Icon");
export const CheckCircleIcon = createIconComponent(CheckCircleIconSvg, "Check Circle Icon");
export const AlertIcon = createIconComponent(AlertIconSvg, "Alert Icon");
export const InfoIcon = createIconComponent(InfoIconSvg, "Info Icon");
export const ErrorIcon = createIconComponent(ErrorIconSvg, "Error Icon");
export const ArrowUpIcon = createIconComponent(ArrowUpIconSvg, "Arrow Up Icon");
export const FolderIcon = createIconComponent(FolderIconSvg, "Folder Icon");
export const ArrowDownIcon = createIconComponent(ArrowDownIconSvg, "Arrow Down Icon");
export const ArrowRightIcon = createIconComponent(ArrowRightIconSvg, "Arrow Right Icon");
export const GroupIcon = createIconComponent(GroupIconSvg, "Group Icon");
export const BoxIconLine = createIconComponent(BoxIconLineSvg, "Box Line Icon");
export const ShootingStarIcon = createIconComponent(ShootingStarIconSvg, "Shooting Star Icon");
export const DollarLineIcon = createIconComponent(DollarLineIconSvg, "Dollar Line Icon");
export const TrashBinIcon = createIconComponent(TrashBinIconSvg, "Trash Bin Icon");
export const AngleUpIcon = createIconComponent(AngleUpIconSvg, "Angle Up Icon");
export const AngleDownIcon = createIconComponent(AngleDownIconSvg, "Angle Down Icon");
export const PencilIcon = createIconComponent(PencilIconSvg, "Pencil Icon");
export const CheckLineIcon = createIconComponent(CheckLineIconSvg, "Check Line Icon");
export const CloseLineIcon = createIconComponent(CloseLineIconSvg, "Close Line Icon");
export const ChevronDownIcon = createIconComponent(ChevronDownIconSvg, "Chevron Down Icon");
export const ChevronUpIcon = createIconComponent(ChevronUpIconSvg, "Chevron Up Icon");
export const PaperPlaneIcon = createIconComponent(PaperPlaneIconSvg, "Paper Plane Icon");
export const LockIcon = createIconComponent(LockIconSvg, "Lock Icon");
export const EnvelopeIcon = createIconComponent(EnvelopeIconSvg, "Envelope Icon");
export const UserIcon = createIconComponent(UserIconSvg, "User Icon");
export const CalenderIcon = createIconComponent(CalenderIconSvg, "Calender Icon");
export const EyeIcon = createIconComponent(EyeIconSvg, "Eye Icon");
export const EyeCloseIcon = createIconComponent(EyeCloseIconSvg, "Eye Close Icon");
export const TimeIcon = createIconComponent(TimeIconSvg, "Time Icon");
export const CopyIcon = createIconComponent(CopyIconSvg, "Copy Icon");
export const ChevronLeftIcon = createIconComponent(ChevronLeftIconSvg, "Chevron Left Icon");
export const UserCircleIcon = createIconComponent(UserCircleIconSvg, "User Circle Icon");
export const TaskIcon = createIconComponent(TaskIconSvg, "Task Icon");
export const ListIcon = createIconComponent(ListIconSvg, "List Icon");
export const TableIcon = createIconComponent(TableIconSvg, "Table Icon");
export const PageIcon = createIconComponent(PageIconSvg, "Page Icon");
export const PieChartIcon = createIconComponent(PieChartIconSvg, "Pie Chart Icon");
export const BoxCubeIcon = createIconComponent(BoxCubeIconSvg, "Box Cube Icon");
export const PlugInIcon = createIconComponent(PlugInIconSvg, "Plug In Icon");
export const DocsIcon = createIconComponent(DocsIconSvg, "Docs Icon");
export const MailIcon = createIconComponent(MailIconSvg, "Mail Icon");
export const HorizontaLDots = createIconComponent(HorizontaLDotsSvg, "Horizontal Dots Icon");
export const ChatIcon = createIconComponent(ChatIconSvg, "Chat Icon");
