import { Product, ProductCategory, ProductCategoryInfo } from '@/lib/types/product';

// Product Categories with detailed information
export const PRODUCT_CATEGORIES: Record<ProductCategory, ProductCategoryInfo> = {
  angle: {
    name: 'Кутник',
    nameEn: 'Aluminium Angle',
    description: 'Алюмінієвий кутник для будівельних та промислових задач',
    descriptionEn: 'Aluminium angle for construction and industrial applications',
    specifications: 'Стандартні розміри, довжина до 6 м, різання в розмір',
    specificationsEn: 'Standard sizes, length up to 6m, cutting to size',
    applications: ['Каркаси', 'Конструкції', 'Меблі'],
    applicationsEn: ['Frames', 'Structures', 'Furniture'],
    image: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80',
  },
  plate: {
    name: 'Пластина',
    nameEn: 'Aluminium Plate / Flat Bar',
    description: 'Алюмінієві пластини та смуги для монтажних та виробничих робіт',
    descriptionEn: 'Aluminium plates and strips for installation and production work',
    specifications: 'Різна товщина, стандартні та нестандартні розміри',
    specificationsEn: 'Various thickness, standard and custom sizes',
    applications: ['Машинобудування', 'Кріпильні елементи'],
    applicationsEn: ['Engineering', 'Fastening elements'],
    image: 'https://images.unsplash.com/photo-1597583190535-852409d75ba2?w=800&q=80',
  },
  channel: {
    name: 'Швелер / Канал',
    nameEn: 'Aluminium Channel',
    description: 'U-подібний алюмінієвий профіль',
    descriptionEn: 'U-shaped aluminium profile',
    specifications: 'EN-стандарти, заводська якість',
    specificationsEn: 'EN standards, factory quality',
    applications: ['Несучі конструкції', 'Монтажні системи'],
    applicationsEn: ['Load-bearing structures', 'Mounting systems'],
    image: 'https://images.unsplash.com/photo-1586864387634-45a5b9f7fbc5?w=800&q=80',
  },
  i_beam: {
    name: 'Двутавр',
    nameEn: 'Aluminium I-beam',
    description: 'Конструкційні профілі для підвищених навантажень',
    descriptionEn: 'Structural profiles for high loads',
    specifications: 'Висока міцність при малій вазі',
    specificationsEn: 'High strength at low weight',
    applications: ['Промислові об\'єкти', 'Будівельні конструкції'],
    applicationsEn: ['Industrial facilities', 'Building structures'],
    image: 'https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=800&q=80',
  },
  t_beam: {
    name: 'Тавр',
    nameEn: 'Aluminium T-beam',
    description: 'Т-подібні конструкційні профілі',
    descriptionEn: 'T-shaped structural profiles',
    specifications: 'Висока міцність при малій вазі',
    specificationsEn: 'High strength at low weight',
    applications: ['Промислові об\'єкти', 'Будівельні конструкції'],
    applicationsEn: ['Industrial facilities', 'Building structures'],
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80',
  },
  round_bar: {
    name: 'Пруток круглий',
    nameEn: 'Aluminium Round Bar',
    description: 'Суцільний круглий алюмінієвий пруток',
    descriptionEn: 'Solid round aluminium bar',
    specifications: 'Різні діаметри, зручний для механічної обробки',
    specificationsEn: 'Various diameters, convenient for machining',
    applications: ['Виробництво деталей', 'Обробка на станках'],
    applicationsEn: ['Parts production', 'Machine processing'],
    image: 'https://images.unsplash.com/photo-1578489758854-f134a358f08b?w=800&q=80',
  },
  t_profile: {
    name: 'Т-подібний профіль',
    nameEn: 'Aluminium T-profile',
    description: 'Універсальний профіль для з\'єднань та каркасів',
    descriptionEn: 'Universal profile for connections and frames',
    specifications: 'Стандартні типорозміри',
    specificationsEn: 'Standard sizes',
    applications: ['Монтажні рішення', 'Конструкційні системи'],
    applicationsEn: ['Mounting solutions', 'Structural systems'],
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80',
  },
  z_profile: {
    name: 'Z-подібний профіль',
    nameEn: 'Aluminium Z-profile',
    description: 'Спеціальний профіль для фасадних та монтажних систем',
    descriptionEn: 'Special profile for facade and mounting systems',
    specifications: 'Можливість виготовлення під замовлення',
    specificationsEn: 'Custom manufacturing available',
    applications: ['Облицювання', 'Будівельні системи'],
    applicationsEn: ['Cladding', 'Building systems'],
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
  },
  tube_round: {
    name: 'Труба кругла',
    nameEn: 'Aluminium Round Tube / Pipe',
    description: 'Порожнисті алюмінієві круглі профілі',
    descriptionEn: 'Hollow aluminium round profiles',
    specifications: 'Різні діаметри та товщина стінки',
    specificationsEn: 'Various diameters and wall thickness',
    applications: ['Конструкції', 'Інженерні системи'],
    applicationsEn: ['Structures', 'Engineering systems'],
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80',
  },
  square_bar: {
    name: 'Пруток квадратний',
    nameEn: 'Aluminium Square Bar',
    description: 'Квадратний алюмінієвий пруток',
    descriptionEn: 'Square aluminium bar',
    specifications: 'Стандартні розміри, різання в розмір',
    specificationsEn: 'Standard sizes, cutting to size',
    applications: ['Металоконструкції', 'Виробництво'],
    applicationsEn: ['Metal structures', 'Manufacturing'],
    image: 'https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=800&q=80',
  },
  sheet: {
    name: 'Лист',
    nameEn: 'Aluminium Sheet',
    description: 'Алюмінієві листи для промислового та комерційного застосування',
    descriptionEn: 'Aluminium sheets for industrial and commercial use',
    specifications: 'Товщина та формат за запитом',
    specificationsEn: 'Thickness and format on request',
    applications: ['Будівництво', 'Дизайн', 'Виробництво'],
    applicationsEn: ['Construction', 'Design', 'Manufacturing'],
    image: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80',
  },
  threshold: {
    name: 'Поріжок',
    nameEn: 'Aluminium Threshold',
    description: 'Готові алюмінієві поріжки та доборні елементи',
    descriptionEn: 'Ready-made aluminium thresholds and accessories',
    specifications: 'Різні форми та покриття',
    specificationsEn: 'Various shapes and coatings',
    applications: ['Інтер\'єрні рішення'],
    applicationsEn: ['Interior solutions'],
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80',
  },
  tube_square: {
    name: 'Труба квадратна',
    nameEn: 'Aluminium Square Tube',
    description: 'Алюмінієві труби квадратного перерізу',
    descriptionEn: 'Aluminium tubes with square cross-section',
    specifications: 'Стандартні розміри, різання в розмір',
    specificationsEn: 'Standard sizes, cutting to size',
    applications: ['Каркаси', 'Інженерні системи', 'Виробничі системи'],
    applicationsEn: ['Frames', 'Engineering systems', 'Production systems'],
    image: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&q=80',
  },
  tube_rectangular: {
    name: 'Труба прямокутна',
    nameEn: 'Aluminium Rectangular Tube',
    description: 'Алюмінієві труби прямокутного перерізу',
    descriptionEn: 'Aluminium tubes with rectangular cross-section',
    specifications: 'Стандартні розміри, різання в розмір',
    specificationsEn: 'Standard sizes, cutting to size',
    applications: ['Каркаси', 'Інженерні системи', 'Виробничі системи'],
    applicationsEn: ['Frames', 'Engineering systems', 'Production systems'],
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
  },
};

// Product Catalog Data
export const CATALOG_PRODUCTS: Product[] = [
  // Aluminium Angle
  {
    id: 'angle-20x20x2',
    category: 'angle',
    name: 'Кутник 20x20x2',
    nameEn: 'Angle 20x20x2mm',
    dimensions: '20x20x2',
    pricePerMeter: 2.85,
    weightPerMeter: 0.32,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'angle-25x25x3',
    category: 'angle',
    name: 'Кутник 25x25x3',
    nameEn: 'Angle 25x25x3mm',
    dimensions: '25x25x3',
    pricePerMeter: 3.50,
    weightPerMeter: 0.41,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'angle-30x30x3',
    category: 'angle',
    name: 'Кутник 30x30x3',
    nameEn: 'Angle 30x30x3mm',
    dimensions: '30x30x3',
    pricePerMeter: 4.20,
    weightPerMeter: 0.49,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'angle-40x40x4',
    category: 'angle',
    name: 'Кутник 40x40x4',
    nameEn: 'Angle 40x40x4mm',
    dimensions: '40x40x4',
    pricePerMeter: 6.80,
    weightPerMeter: 0.87,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Plate / Flat Bar
  {
    id: 'plate-20x3',
    category: 'plate',
    name: 'Пластина 20x3',
    nameEn: 'Flat Bar 20x3mm',
    dimensions: '20x3',
    pricePerMeter: 2.20,
    weightPerMeter: 0.16,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'plate-30x5',
    category: 'plate',
    name: 'Пластина 30x5',
    nameEn: 'Flat Bar 30x5mm',
    dimensions: '30x5',
    pricePerMeter: 4.50,
    weightPerMeter: 0.41,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'plate-50x5',
    category: 'plate',
    name: 'Пластина 50x5',
    nameEn: 'Flat Bar 50x5mm',
    dimensions: '50x5',
    pricePerMeter: 7.20,
    weightPerMeter: 0.68,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Channel
  {
    id: 'channel-20x20x2',
    category: 'channel',
    name: 'Швелер 20x20x2',
    nameEn: 'Channel 20x20x2mm',
    dimensions: '20x20x2',
    pricePerMeter: 3.80,
    weightPerMeter: 0.45,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'channel-30x30x3',
    category: 'channel',
    name: 'Швелер 30x30x3',
    nameEn: 'Channel 30x30x3mm',
    dimensions: '30x30x3',
    pricePerMeter: 6.50,
    weightPerMeter: 0.78,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium I-beam
  {
    id: 'i-beam-40x40x3',
    category: 'i_beam',
    name: 'Двутавр 40x40x3',
    nameEn: 'I-beam 40x40x3mm',
    dimensions: '40x40x3',
    pricePerMeter: 8.50,
    weightPerMeter: 1.02,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'i-beam-60x60x4',
    category: 'i_beam',
    name: 'Двутавр 60x60x4',
    nameEn: 'I-beam 60x60x4mm',
    dimensions: '60x60x4',
    pricePerMeter: 14.50,
    weightPerMeter: 1.85,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Round Bar
  {
    id: 'round-bar-10',
    category: 'round_bar',
    name: 'Пруток круглий Ø10',
    nameEn: 'Round Bar Ø10mm',
    dimensions: 'Ø10',
    pricePerMeter: 1.85,
    weightPerMeter: 0.21,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'round-bar-16',
    category: 'round_bar',
    name: 'Пруток круглий Ø16',
    nameEn: 'Round Bar Ø16mm',
    dimensions: 'Ø16',
    pricePerMeter: 4.50,
    weightPerMeter: 0.55,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'round-bar-20',
    category: 'round_bar',
    name: 'Пруток круглий Ø20',
    nameEn: 'Round Bar Ø20mm',
    dimensions: 'Ø20',
    pricePerMeter: 6.80,
    weightPerMeter: 0.86,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Round Tube
  {
    id: 'tube-round-20x2',
    category: 'tube_round',
    name: 'Труба кругла Ø20x2',
    nameEn: 'Round Tube Ø20x2mm',
    dimensions: 'Ø20x2',
    pricePerMeter: 2.95,
    weightPerMeter: 0.31,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-round-25x2',
    category: 'tube_round',
    name: 'Труба кругла Ø25x2',
    nameEn: 'Round Tube Ø25x2mm',
    dimensions: 'Ø25x2',
    pricePerMeter: 3.65,
    weightPerMeter: 0.40,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-round-30x2',
    category: 'tube_round',
    name: 'Труба кругла Ø30x2',
    nameEn: 'Round Tube Ø30x2mm',
    dimensions: 'Ø30x2',
    pricePerMeter: 4.35,
    weightPerMeter: 0.49,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Square Bar
  {
    id: 'square-bar-10',
    category: 'square_bar',
    name: 'Пруток квадратний 10x10',
    nameEn: 'Square Bar 10x10mm',
    dimensions: '10x10',
    pricePerMeter: 2.15,
    weightPerMeter: 0.27,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'square-bar-15',
    category: 'square_bar',
    name: 'Пруток квадратний 15x15',
    nameEn: 'Square Bar 15x15mm',
    dimensions: '15x15',
    pricePerMeter: 4.65,
    weightPerMeter: 0.61,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Sheet
  {
    id: 'sheet-1mm',
    category: 'sheet',
    name: 'Лист 1мм',
    nameEn: 'Sheet 1mm',
    dimensions: '1000x2000x1',
    pricePerKg: 4.20,
    weightPerMeter: 2.7,
    standardLengths: [1, 2, 3],
    inStock: true,
    material: '1050-H14',
    finish: 'Mill finish',
  },
  {
    id: 'sheet-2mm',
    category: 'sheet',
    name: 'Лист 2мм',
    nameEn: 'Sheet 2mm',
    dimensions: '1000x2000x2',
    pricePerKg: 4.20,
    weightPerMeter: 5.4,
    standardLengths: [1, 2, 3],
    inStock: true,
    material: '1050-H14',
    finish: 'Mill finish',
  },
  {
    id: 'sheet-3mm',
    category: 'sheet',
    name: 'Лист 3мм',
    nameEn: 'Sheet 3mm',
    dimensions: '1000x2000x3',
    pricePerKg: 4.20,
    weightPerMeter: 8.1,
    standardLengths: [1, 2, 3],
    inStock: true,
    material: '1050-H14',
    finish: 'Mill finish',
  },

  // Aluminium Square Tube
  {
    id: 'tube-square-20x20x2',
    category: 'tube_square',
    name: 'Труба квадратна 20x20x2',
    nameEn: 'Square Tube 20x20x2mm',
    dimensions: '20x20x2',
    pricePerMeter: 3.45,
    weightPerMeter: 0.43,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-square-25x25x2',
    category: 'tube_square',
    name: 'Труба квадратна 25x25x2',
    nameEn: 'Square Tube 25x25x2mm',
    dimensions: '25x25x2',
    pricePerMeter: 4.20,
    weightPerMeter: 0.54,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-square-30x30x2',
    category: 'tube_square',
    name: 'Труба квадратна 30x30x2',
    nameEn: 'Square Tube 30x30x2mm',
    dimensions: '30x30x2',
    pricePerMeter: 5.20,
    weightPerMeter: 0.65,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Rectangular Tube
  {
    id: 'tube-rect-20x40x2',
    category: 'tube_rectangular',
    name: 'Труба прямокутна 20x40x2',
    nameEn: 'Rectangular Tube 20x40x2mm',
    dimensions: '20x40x2',
    pricePerMeter: 4.80,
    weightPerMeter: 0.65,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-rect-30x60x2',
    category: 'tube_rectangular',
    name: 'Труба прямокутна 30x60x2',
    nameEn: 'Rectangular Tube 30x60x2mm',
    dimensions: '30x60x2',
    pricePerMeter: 7.50,
    weightPerMeter: 0.97,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
];
